<?php
/**
 * Optty_Settings
 *
 * @package Optty_Settings
 */

namespace Optty\classes;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Abstraction for using WP Settings API
 */
class Settings {

	private const OPTIONS_KEY = 'woocommerce_optty_settings'; // Generated by WooCommerce in WC_Settings_API::get_option_key().

	/**
	 * Setting values from get_option.
	 *
	 * @var array
	 */
	private static array $settings;

	/**
	 * __get
	 *
	 * @param string $key Key.
	 *
	 * @return string|null
	 */
	public static function get( string $key ): ?string {
		self::$settings = (array) get_option( self::OPTIONS_KEY, array() );

		$value = self::$settings[ $key ] ?? null;
		return apply_filters( 'optty_wc_settings_' . $key, $value );
	}
}
